(()=>{"use strict";
const c=document.getElementById("game"),x=c.getContext("2d"),hud=document.getElementById("hud"),menu=document.getElementById("menu"),pauseS=document.getElementById("pauseScreen"),over=document.getElementById("over");
let W=innerWidth,H=innerHeight,dpr=1,state="menu",mice=[],parts=[],score=0,caught=0,combo=0,last=0,spawn=0,mode="normal",best=Number(localStorage.getItem("madMiceBest")||0);
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+"px";c.style.height=H+"px";x.setTransform(dpr,0,0,dpr,0,0)}addEventListener("resize",resize);resize();
const R=(a,b)=>a+Math.random()*(b-a);
function hudUpdate(){document.getElementById("score").textContent=score;document.getElementById("combo").textContent="×"+Math.max(1,combo);document.getElementById("best").textContent=best;if(score>best){best=score;localStorage.setItem("madMiceBest",best)}}
function start(m){mode=m;mice=[];parts=[];score=0;caught=0;combo=0;spawn=1;state="play";menu.classList.add("hidden");over.classList.add("hidden");pauseS.classList.add("hidden");hud.classList.remove("hidden");hudUpdate();last=performance.now();requestAnimationFrame(loop)}
function addMouse(){let left=Math.random()<.5,level=1+Math.floor(score/15),speed=R(55,95)+level*2; mice.push({x:left?-50:W+50,y:R(110,H-80),vx:left?speed:-speed,phase:R(0,7),size:R(.9,1.12),gold:Math.random()<.08})}
function drawBg(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,"#65767a");g.addColorStop(.55,"#526367");g.addColorStop(1,"#354447");x.fillStyle=g;x.fillRect(0,0,W,H);x.globalAlpha=.07;x.strokeStyle="#fff";for(let i=0;i<W;i+=90){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}for(let i=0;i<H;i+=90){x.beginPath();x.moveTo(0,i);x.lineTo(W,i);x.stroke()}x.globalAlpha=1}
function mouse(m){let y=m.y+Math.sin(m.phase)*8;x.save();x.translate(m.x,y);x.scale(m.vx<0?-m.size:m.size,m.size);x.fillStyle="#0003";x.beginPath();x.ellipse(0,26,30,6,0,0,7);x.fill();x.strokeStyle=m.gold?"#e3c77a":"#aeb7b8";x.lineWidth=4;x.beginPath();x.arc(-27,7,19,.4,4.8);x.stroke();x.fillStyle=m.gold?"#cbb574":"#aab3b5";x.beginPath();x.ellipse(0,8,29,19,0,0,7);x.fill();x.fillStyle=m.gold?"#d9c487":"#bdc5c7";x.beginPath();x.arc(28,5,17,0,7);x.fill();x.beginPath();x.arc(25,-9,11,0,7);x.arc(37,-7,10,0,7);x.fill();x.fillStyle="#101719";x.beginPath();x.arc(36,1,2.5,0,7);x.fill();x.fillStyle="#e7a1ab";x.beginPath();x.arc(44,8,3,0,7);x.fill();x.restore()}
function burst(px,py){for(let i=0;i<10;i++){let a=R(0,7),s=R(20,70);parts.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:R(2,4),life:.5})}}
function catchM(m,px,py){m.dead=1;combo++;caught++;score+=m.gold?5:1;if(score>best){best=score;localStorage.setItem("madMiceBest",best)}burst(px,py);mice=mice.filter(q=>q!==m);hudUpdate()}
function loop(t){if(state!=="play")return;let dt=Math.min((t-last)/1000,.04);last=t;spawn+=dt;let interval=Math.max(.72,1.25-Math.floor(score/15)*.035);if(spawn>interval){spawn=0;addMouse();if(score>30&&Math.random()<.12)addMouse()}drawBg();for(const m of [...mice]){m.phase+=dt*2.5;m.x+=m.vx*dt;mouse(m);if(m.x<-80||m.x>W+80){mice=mice.filter(q=>q!==m);combo=0;hudUpdate()}}for(const p of parts){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt;x.globalAlpha=Math.max(0,p.life/.5);x.fillStyle="#f7eeee";x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()}x.globalAlpha=1;parts=parts.filter(p=>p.life>0);requestAnimationFrame(loop)}
c.addEventListener("pointerdown",e=>{if(state!=="play")return;let r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;for(let i=mice.length-1;i>=0;i--){let m=mice[i],yy=m.y+Math.sin(m.phase)*8,dx=px-m.x,dy=py-yy;if(dx*dx+dy*dy<52*52){catchM(m,px,py);break}}});
document.getElementById("play").onclick=()=>start("normal");document.getElementById("endless").onclick=()=>start("endless");document.getElementById("again").onclick=()=>start(mode);document.getElementById("home").onclick=()=>{state="menu";over.classList.add("hidden");hud.classList.add("hidden");menu.classList.remove("hidden")};document.getElementById("pause").onclick=()=>{if(state==="play"){state="pause";pauseS.classList.remove("hidden")}};document.getElementById("resume").onclick=()=>{state="play";pauseS.classList.add("hidden");last=performance.now();requestAnimationFrame(loop)};document.getElementById("quit").onclick=()=>document.getElementById("home").click();
})();